### ISSUE TITLE
npm test failure

### ISSUE THREAD

**Issue by rharing** [xogeny/ts-jest-sample#5]
npm 5.6.0 node 8.10.0 on windows same issue on linux node 10.9.0 npm 6.4.1
just cloned it did a npm i then npm test and crash:
which is annoying be cause i cloned your project because of the same error
FAIL  __tests__\base.spec.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.495s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

**Comment by xogeny** [comment]
This is fixed with #6, right?  So ok to close this?

**Comment by rharing** [comment]
yes can be closed
